"""Create new table

Revision ID: 615a11715ad8
Revises: 09f9eff90d81
Create Date: 2023-07-10 16:54:11.670026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615a11715ad8'
down_revision = '09f9eff90d81'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_ms_user() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ms_user() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

